name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate library
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libjourney_model_parser.so
          path: target/release/libjourney_model_parser.so

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate library
        run: cargo build --release --target x86_64-pc-windows-gnu
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: journey_model_parser.dll
          path: target/x86_64-pc-windows-gnu/release/journey_model_parser.dll